#
# Copyright (c) 2018, 2019 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

kind: Service
apiVersion: v1
metadata:
  name: helidon-db-status
  namespace: dbstat-helidon
  labels:
    app: helidon-db-status
spec:
  type: NodePort
  selector:
    app: helidon-db-status
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-db-status
  namespace: dbstat-helidon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidon-db-status
  template:
    metadata:
      labels:
        app: helidon-db-status
        version: v1
    spec:
      containers:
      - name: helidon-db-status
        image: helidon-db-status
        imagePullPolicy: Always
        env:
        - name: DBUSR
          valueFrom:
            secretKeyRef:
              name: k8spdb-secret
              key: pdb_admin
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: k8spdb-secret
              key: pdb_pwd
        - name: DBURL
          valueFrom:
            configMapKeyRef:
              name: k8spdb-config
              key: pdb_conn
        ports:
        - containerPort: 8080
---
