# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: keycloak-helidon-component
  namespace: keycloak-helidon
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoHelidonWorkload
    metadata:
      name: keycloak-helidon-workload
      labels:
        app: keycloak-helidon
        version: v1
    spec:
      deploymentTemplate:
        metadata:
          name: keycloak-helidon-deployment
        podSpec:
          containers:
            - name: keycloak-helidon-container
              image: docker.io/ilfur/helidon-keycloak
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  name: http
#          imagePullSecrets:
#              - name: docker.io
